name = "EngineKinematics"
uuid = "0b44c29b-429e-4def-8932-c80589416a57"
authors = ["C. Naaktgeboren"]
version = "0.1.0"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
